### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by mk299** [mk299/chat-space#9]
# IPアドレス
52.196.133.63

**Comment by mo1015** [comment]
ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）

**Comment by mk299** [comment]
ありがとうございます！
引き続きがんばります。
